### ISSUE TITLE
Can`t load source plugin

### ISSUE THREAD

**Issue by ghost** [fengberd/FDevTools#4]
```
Server plugin folder
\test_src
　├plugin.yml
　└src
　　└main
　　　　├resources
　　　　|　　　└plugin.yml
　　　　└java
　　　　　 └test
　　　　　　　└plugin
　　　　　　　　　└jp
　　　　　　　　　　└playername
　　　　　　　　　　　　　　└playername.java
```

bash

``` bash
2016-8-29 20:55:42 [INFO] [FDevTools] Loading source plugin "TansuServerMainPlugin"
2016-8-29 20:55:42 [ALERT] java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
    at java.util.LinkedHashMap$LinkedValueIterator.next(Unknown Source)
    at cn.nukkit.Server.enablePlugins(Server.java:605)
    at cn.nukkit.Server.<init>(Server.java:382)
    at cn.nukkit.Nukkit.main(Nukkit.java:65)
```

**Comment by fengberd** [comment]
Try this format
\test_src
　├plugin.yml
　└src
　　 └test
　　　 └plugin
　　　 　└jp
　　　　 　└playername
　　　　 　　└playername.java

**Comment by ghost** [comment]
Ok, thank you

**Comment by XDqrkneZ** [comment]
do you really need that much folders? holy crap
