### ISSUE TITLE
Can`t load plugin

### ISSUE THREAD

**Issue by ghost** [fengberd/FDevTools#6]
**FDevTools ver:** 2016-11-13_17-36
**Can`t load plugin:** [pls download](https://drive.google.com/file/d/0B7sMAXgAodGiLXpWYjdJSGJKd0E/view?usp=sharing)

Sorry to ask a question over and over.

**Comment by fengberd** [comment]
You should use path
test\src\test\plugin
instead of test\src\main\java\test\plugin
....



Best Regards,
FENGberd

**Comment by ghost** [comment]
I fixed it, but received error
> [ALERT] java.util.ConcrrentModificationExeption
at java.util.LinkedHashMao$LinkedHashIterator.nextNode(UnknownSource)
at java.util.LinkedHashMao$LinkedValueIterator.next(UnknownSource)
at cn.nukkit.Server.enablePlugins(Server.java:612)
at cn.nukkit.Server.<init>(Server.java:388)
at cn.nukkit.Nukkit.main(Nukkit.java:65)
...
[INFO] Stopping other threads

**Comment by fengberd** [comment]
It works well on my computer,just check your code please.


Best Regards,
FENGberd

**Comment by ghost** [comment]
Other plugins were affected.
thank you.
